### ISSUE TITLE
Add aliases?

### ISSUE THREAD

**Issue by alexherbo2** [alexherbo2/plug.kak#7]
- `plug-install` (`pi`)
- `plug-upgrade` (`pu`)
- `plug-execute` (`px`)
- `plug-clean` (`pd`)

**Comment by SeerLite** [comment]
I think it's better to only have the long commands. Maybe add an example in the README with the aliases added in `plug`s `plug` config?

**Comment by alexherbo2** [comment]
I would like to improve the workflow for installing new plugins.

Currently I open my kakrc, enter the `plug` in it, select the command and source it with `: <c-r>.<ret>`, `plug-install` and restart Kakoune.

A single command unifying that could be nice, so we don’t need the other commands interactively too frequently.

**Comment by SeerLite** [comment]
I see what you mean... What do you think of accepting optional arguments to `plug-install`? Those would then be passed to `plug` before running git/install.
And then just alias `plug-install` to `pi`.

Speaking of restarting Kakoune, I'd love it if Kakoune just had an easier mechanism for re-sourcing the config without having to completely restart the server. I wonder if it's possible at all? To just clear the state of everything and source it all again?

Oh and also thank you for telling me about the `.` register! I've been doing `y :<c-r>"<ret>` this whole time lol

**Comment by alexherbo2** [comment]
You might like [evaluate-selections.kak].  About the implementation, it uses `-itersel` instead of the prompt, so that it works with multiple selections.

[evaluate-selections.kak]: https://github.com/alexherbo2/evaluate-selections.kak

**Comment by alexherbo2** [comment]
@SeerLite Can you test the `plug` user mode?

If you have `u` aliased to `enter-user-mode`, you can do:

``` kak
u plug
```

**Comment by SeerLite** [comment]
Hey! Sorry for the delay.

I completely forgot before that in order to install a plugin it's necessary to edit kakrc (to call `plug`). I only realized that now that you implemented the user mode.

Personally, I'm not a fan of automating anything that has to do with editing kakrc. However, it does look like a good feature and seems to work pretty well, so I'm sure other people might like it!

**Comment by alexherbo2** [comment]
I agree.  I don’t like it either because it is a bit intruisive.

How about instead opening a scratch buffer with the content the user can copy to its kakrc?

Emacs has a similar feature called “[Narrowing]”.

[Narrowing]: https://gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html

**Comment by SeerLite** [comment]
Yeah that sounds better! I was thinking you could even use registers directly and fill `"p` with the right command, but an external buffer sounds like a much better idea.

**Comment by alexherbo2** [comment]
For the interface, I was thinking about a light format telling the user to press <kbd>Enter</kbd> in the buffer to open the kakrc with the content copied.  Something similar on web pages, with a “Click to copy” button.

**Comment by alexherbo2** [comment]
@SeerLite Can you test the new command?

**Comment by SeerLite** [comment]
Wow, it's really smooth! Good job setting it up!

I have some mixed feelings about all this:

On one hand, I think it's really great. The command works really well and feels smooth and interactive.
On the other hand, I feel like this is just having to write to kakrc but with extra (or just reordered) steps.

I'm gonna try to use it a bit more (good thing I found some new plugins to play around with). I do have some ideas to improve it.

Oh, I almost forgot: it's not symlinking the newly installed plugins! It's because `$kak_autoload_plugins_path` isn't set inside `plug-install-interactive`. Are you planning on making that an option like `plug_install_path`?

**Comment by alexherbo2** [comment]
Yep, I added a few paths.  They are not intended to be edited, but to make the plugin more maintainable.

I took the occasion to unify the plugins under a single path: the core lives under the managed `~/.config/kak/autoload/plugins` directory.  Anything above is not touched by plug.kak.

**Comment by alexherbo2** [comment]
@SeerLite `px<space>plug git pull` generally expands to `plug-execute` with the recent change in <kbd>Space</kbd> from @mawww, so maybe we can close it?
